(() => {
'use strict';
const seed=()=>({authenticated:false,user:'joao',accounts:[{name:'joao',password:'minhasenha123'}],cards:[{id:'c1',front:'How are you?',back:'Como você está?'},{id:'c2',front:'What does “take your time” mean?',back:'Significa “sem pressa”: faça no seu ritmo.'},{id:'c3',front:'Where is the train station?',back:'Onde fica a estação de trem?'}],decks:[{id:'d1',name:'Inglês cotidiano',cardIds:['c1','c2']},{id:'d2',name:'Viagens',cardIds:['c1','c3']},{id:'d3',name:'Próximas ideias',cardIds:[]}],session:null,dirty:false,scenario:null});
let state=seed(), route='entrar', callbacks=[], busy=false;
const view=document.querySelector('#view'), dialog=document.querySelector('#confirmation');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(text,target,variant='')=>`<a href="#${esc(target)}" data-route="${esc(target)}" class="${variant?'btn '+esc(variant):''}">${esc(text)}</a>`;
const button=(text,action,variant='secondary')=>`<button type="button" class="btn ${esc(variant)}" data-action="${esc(action)}">${esc(text)}</button>`;
function notify(message,type='success'){const node=document.querySelector('#feedback');node.className=type;node.textContent=message;node.setAttribute('role',type==='error'?'alert':'status');}
function confirm({title,message,confirmLabel='Confirmar',onConfirm}){if(dialog.open)return;const previous=document.activeElement;document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-message').textContent=message;document.querySelector('#dialog-confirm').textContent=confirmLabel;dialog.showModal();document.querySelector('#dialog-cancel').focus();dialog.onkeydown=event=>{if(event.key==='Tab'){const first=document.querySelector('#dialog-cancel'),last=document.querySelector('#dialog-confirm');if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};const finish=()=>{dialog.close();if(previous?.isConnected)previous.focus();};document.querySelector('#dialog-cancel').onclick=finish;document.querySelector('#dialog-confirm').onclick=()=>{finish();onConfirm();};dialog.oncancel=event=>{event.preventDefault();finish();};}
function guarded(action){if(busy){notify('Aguarde a conclusão da operação.');return;}if(state.dirty||state.session?.active){const studying=state.session?.active;confirm({title:studying?'Interromper estudo?':'Descartar alterações?',message:studying?'O progresso desta sessão será descartado. Nenhum resumo será gerado.':'As alterações ainda não foram salvas. Ao sair, elas serão descartadas.',confirmLabel:studying?'Interromper estudo':'Descartar alterações',onConfirm:()=>{state.dirty=false;state.session=null;action();}});}else action();}
function go(target){if(state.session?.active && target===`estudo/${state.session.deckId}/sessao` && !state.dirty){navigate(target);return;}guarded(()=>navigate(target));}
function navigate(target){if(target==='sair'){state.authenticated=false;state.session=null;target='entrar';notify('Você saiu.');}route=target;if(!state.authenticated&&!['entrar','cadastro','cadastro/sucesso','galeria'].includes(route))route='entrar';history.pushState({route},'', '#'+route);render();}
async function operation(control,callback){if(busy)return false;busy=true;const original=control?.textContent;if(control){control.disabled=true;control.textContent='Aguarde…';control.setAttribute('aria-busy','true');}const scenario=state.scenario;state.scenario=null;await new Promise(resolve=>setTimeout(resolve,scenario==='pending'?1800:450));try{if(scenario==='error'){notify('Não foi possível concluir. Seus dados foram mantidos. Tente novamente.','error');return false;}busy=false;await callback();return true;}finally{busy=false;if(control?.isConnected){control.disabled=false;control.textContent=original;control.removeAttribute('aria-busy');}}}
function notFound(){return `<section class="empty"><h1>Recurso não encontrado</h1><p>Este cartão ou baralho não está disponível.</p>${link('Voltar aos baralhos','baralhos','primary')}</section>`;}
const scenarios=[
['Acesso',[['Entrada','entrar'],['Credenciais inválidas','entrar','invalid'],['Serviço indisponível','entrar','login-error'],['Envio pendente','entrar','pending'],['Cadastro','cadastro'],['Falha ao cadastrar','cadastro','error'],['Cadastro concluído','cadastro/sucesso']]],
['Acervo',[['Baralhos','baralhos'],['Baralhos vazios','baralhos','empty-decks'],['Novo baralho','baralhos/novo'],['Detalhe do baralho','baralhos/d1'],['Renomear baralho','baralhos/d1/editar'],['Adicionar cartões existentes','baralhos/d1/adicionar'],['Cartões','cartoes'],['Cartões vazios','cartoes','empty-cards'],['Novo cartão','cartoes/novo'],['Editar cartão compartilhado','cartoes/c1/editar'],['Falha ao salvar cartão','cartoes/c1/editar','error'],['Operação pendente','cartoes/c1/editar','pending'],['Conteúdo longo e acervo extenso','cartoes','long'],['Recurso não encontrado','baralhos/ausente'],['Confirmação de descarte','cartoes/c1/editar','discard'],['Confirmação de exclusão','cartoes','delete']]],
['Estudo',[['Configurar quantidade','estudo/d1/configurar'],['Baralho vazio','estudo/d3/configurar'],['Frente · resposta oculta','estudo/d1/sessao','study'],['Resposta revelada','estudo/d1/sessao','revealed'],['Interrupção','estudo/d1/sessao','interrupt'],['Resumo da sessão','estudo/d1/resumo','summary']]],
['Estados e propostas',[['Carregamento','baralhos','loading'],['Falha de carregamento','baralhos','load-error'],['Sucesso','baralhos','success'],['Explorações futuras','exploracoes']]]];
function gallery(){callbacks.push(()=>{document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>openCase(Number(b.dataset.case)));document.querySelectorAll('[data-accent-choice]').forEach(b=>b.onclick=()=>{document.documentElement.dataset.accent=b.dataset.accentChoice;render();});});let n=0;return `<div class="page-head"><div><p class="eyebrow">Ferramentas de revisão</p><h1>Galeria de telas e estados</h1><p class="muted">Cada cenário restaura os exemplos. Os dados duram apenas nesta página aberta.</p></div></div><section class="card"><h2>Identidade visual</h2><p>Escuro com destaque azul. Compare a alternativa verde nas mesmas telas.</p><div class="actions">${['azul','verde'].map(a=>`<button class="btn secondary" data-accent-choice="${a}" aria-pressed="${document.documentElement.dataset.accent===a}">Destaque ${a}</button>`).join('')}</div></section>${scenarios.map(([title,cases])=>`<section class="gallery-group"><h2>${title}</h2><div class="grid">${cases.map(([name])=>`<button class="btn secondary" data-case="${n++}">${name}</button>`).join('')}</div></section>`).join('')}<p class="muted">Nos formulários, envie campos vazios para revisar a validação. Nos detalhes, remova vínculos e confirme exclusões. Os cenários de falha permitem tentar novamente, preservando o conteúdo informado.</p>`;}
function openCase(index){document.querySelector('#feedback').textContent='';const [,target,scenario]=scenarios.flatMap(g=>g[1])[index];state=seed();state.authenticated=!target.startsWith('entrar')&&!target.startsWith('cadastro');state.scenario=scenario||null;if(scenario==='empty-decks')state.decks=[];if(scenario==='empty-cards'){state.cards=[];state.decks.forEach(d=>d.cardIds=[]);}if(scenario==='long'){state.cards=Array.from({length:40},(_,i)=>({id:'c'+(i+1),front:`Cartão ${i+1}: Como praticar um conteúdo extenso? `+'Exemplo de uma pergunta que precisa quebrar linhas sem perder informação. '.repeat(8),back:'Resposta com detalhes, acentuação e uma palavra extensa: '+ 'conteúdo'.repeat(40)}));}if(['study','revealed','interrupt','summary'].includes(scenario)){const cards=state.cards.slice(0,2);state.session={deckId:'d1',cards,index:scenario==='summary'?2:0,revealed:scenario==='revealed',answers:scenario==='summary'?cards.map((c,i)=>({...c,correct:i===0})):[],active:scenario!=='summary'};state.scenario=null;}navigate(target);if(scenario==='success')notify('Baralho criado com sucesso.');if(scenario==='discard'){const input=view.querySelector('#card-front');input.value+=' · edição pendente';input.dispatchEvent(new Event('input',{bubbles:true}));go('cartoes');}if(scenario==='interrupt')go('baralhos');if(scenario==='delete')view.querySelector('[data-delete-card]')?.click();}
function render(){callbacks=[];document.querySelector('#header').innerHTML=`<span class="wordmark">memorization<span>●</span></span>${state.authenticated?`<nav class="nav" aria-label="Principal">${['baralhos','cartoes'].map(r=>`<a href="#${r}" data-route="${r}" ${route.startsWith(r)?'aria-current="page"':''}>${r==='baralhos'?'Baralhos':'Cartões'}</a>`).join('')}</nav><button id="logout" class="btn secondary" data-route="sair">Sair</button>`:''}`;const ctx={state,route,esc,go,render,after:fn=>callbacks.push(fn),notify,confirm,operation,button,link,notFound};let content;if(route==='galeria')content=gallery();else if(['loading','load-error'].includes(state.scenario)){const loading=state.scenario==='loading';content=`<section class="empty"><h1>${loading?'Carregando baralhos…':'Não foi possível carregar'}</h1><p>${loading?'Aguarde enquanto buscamos seu acervo.':'Seu acervo está preservado. Tente novamente.'}</p>${loading?'<div class="loading" role="status" aria-label="Carregando"></div>':''}<button id="retry" class="btn primary">${loading?'Concluir carregamento':'Tentar novamente'}</button></section>`;callbacks.push(()=>document.querySelector('#retry').onclick=()=>{state.scenario=null;render();});}else content=window.Access?.render(ctx)??window.Collection?.render(ctx)??window.Study?.render(ctx)??notFound();view.innerHTML=content;callbacks.forEach(fn=>fn());const title=view.querySelector('h1');if(title){title.tabIndex=-1;title.focus();}document.title=(title?.textContent||'Memorization')+' — Memorization';}
document.addEventListener('click',e=>{const target=e.target.closest('[data-route]');if(target){e.preventDefault();document.querySelector('#feedback').textContent='';go(target.dataset.route);}});document.querySelector('#reset').onclick=()=>guarded(()=>{state=seed();notify('Demonstração reiniciada.');navigate('entrar');});window.addEventListener('popstate',()=>{const target=location.hash.slice(1)||'entrar';history.replaceState({route},'','#'+route);go(target);});window.addEventListener('beforeunload',e=>{if(state.dirty||state.session?.active){e.preventDefault();e.returnValue='';}});history.replaceState({route},'','#entrar');render();
})();
