import { chromium, expect } from '@playwright/test';
const browser = await chromium.launch();
try {
const page = await browser.newPage();
await page.goto(new URL('./index.html', import.meta.url).href);
await page.getByRole('button',{name:'Entrar',exact:true}).click();
await page.getByRole('link',{name:'Criar baralho',exact:true}).click();
await page.getByRole('button',{name:'Criar baralho',exact:true}).click();
await expect(page.getByRole('alert')).toContainText('Preencha');
await page.getByLabel('Nome do baralho', {exact:true}).fill('Teste acervo');
await page.getByRole('button',{name:'Criar baralho',exact:true}).click();
await expect(page.getByRole('heading',{name:'Teste acervo',exact:true})).toBeVisible();
await page.getByRole('link',{name:'Adicionar cartões existentes',exact:true}).first().click();
await page.getByRole('button',{name:'Adicionar ao baralho',exact:true}).first().click();
await expect(page.locator('#view [data-add]')).toHaveCount(2);
await page.getByRole('link',{name:'← Voltar ao baralho',exact:true}).click();
await expect(page.locator('[data-remove]')).toHaveCount(1);
await page.getByRole('button',{name:'Remover deste baralho',exact:true}).click();
await expect(page.getByRole('heading',{name:'Este baralho está vazio',exact:true})).toBeVisible();
await page.getByRole('button',{name:'Excluir baralho',exact:true}).click();
await page.locator('#dialog-confirm').click();
await expect(page.getByRole('heading',{name:'Baralhos',exact:true})).toBeVisible();
await page.getByRole('link',{name:'Cartões',exact:true}).click();
await expect(page.locator('[data-delete-card]')).toHaveCount(3);
await page.getByRole('link',{name:'Editar cartão',exact:true}).first().click();
await page.getByLabel('Frente',{exact:true}).fill('Alteração compartilhada');
await page.getByRole('link',{name:'Cancelar',exact:true}).click();
await expect(page.locator('#dialog-cancel')).toBeFocused();
await page.keyboard.press('Escape');
await expect(page.getByRole('link',{name:'Cancelar',exact:true})).toBeFocused();
await expect(page.getByLabel('Frente',{exact:true})).toHaveValue('Alteração compartilhada');
await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();
await expect(page.getByRole('heading',{name:'Alteração compartilhada',exact:true})).toBeVisible();
await page.getByRole('link',{name:'Inglês cotidiano',exact:true}).first().click();
await expect(page.getByRole('heading',{name:'Alteração compartilhada',exact:true})).toBeVisible();
await page.getByRole('link',{name:'Viagens',exact:true}).first().click();
await expect(page.getByRole('heading',{name:'Alteração compartilhada',exact:true})).toBeVisible();
await page.getByRole('link',{name:'Cartões',exact:true}).click();
await page.getByRole('button',{name:'Excluir cartão',exact:true}).first().click();
await expect(page.locator('#dialog-message')).toContainText('2 baralhos');
await page.locator('#dialog-confirm').click();
await expect(page.locator('[data-delete-card]')).toHaveCount(2);
await page.getByRole('link',{name:'Baralhos',exact:true}).click();
await expect(page.getByRole('link',{name:'Ver baralho',exact:true})).toHaveCount(3);
await page.getByRole('link',{name:'Cartões',exact:true}).click();
await page.getByRole('link',{name:'Criar cartão',exact:true}).click();
await page.getByLabel('Frente',{exact:true}).fill('Novo cartão');
await page.getByLabel('Verso',{exact:true}).fill('Resposta nova');
await page.getByRole('button',{name:'Criar cartão',exact:true}).click();
await expect(page.locator('[data-delete-card]')).toHaveCount(3);
await page.getByRole('link',{name:'Galeria de revisão',exact:true}).click();
await page.getByRole('button',{name:'Falha ao salvar cartão',exact:true}).click();
await page.getByLabel('Frente',{exact:true}).fill('Conteúdo preservado após erro');
await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();
await expect(page.locator('#feedback')).toContainText('Tente novamente');
await expect(page.getByLabel('Frente',{exact:true})).toHaveValue('Conteúdo preservado após erro');
await page.getByRole('button',{name:'Salvar alterações',exact:true}).click();
await expect(page.getByRole('heading',{name:'Conteúdo preservado após erro',exact:true})).toBeVisible();
console.log('Acervo integrado: CRUD, vínculos, edição compartilhada, preservação nas exclusões, descarte, foco, falha e nova tentativa passaram.');
} finally {
  await browser.close();
}
